---
title: "MSC_survival"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=F, warning=F, message=F, error=F}
#1. Installing packages
#install.packages("data.table")
#install.packages("ggplot2")
#install.packages("cowplot")
#install.packages("RColorBrewer")
#install.packages("gridExtra")
#install.packages("pander")

#2. Attaching packages
library(data.table)
library(ggplot2)
library(cowplot)
library(gridExtra)
library(grid)

library(RColorBrewer)

library(knitr)
library(pander)

rm(list=ls())

#Importing function for sharing legend 
source("/home/ramhak/Dropbox/PHD/PAPER I/R_v2/Function_directory/get_legend.R")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Files to import
csv_to_import <- as.list(dir()[grep("Summary",dir())])
#2. Function which imports each file in the file name list and adds the RH.index
import_function <- function(file_name){
  data_table_temp <- fread(file_name)  
  data_table_temp <- data_table_temp[,RH.index:= substr(file_name, regexpr("RH", file_name)[1]+2,regexpr("RH", file_name)[1]+4)]
  
  return(data_table_temp)
}
#3. Calling the function and binding by row
DT <- do.call(rbind, lapply(csv_to_import, function(list.object){import_function(list.object)}))
#4. Removing undesired columns
remove_cols = c("Slice", "Total Area", "Average Size", "%Area", "Mean")
DT[,remove_cols] =NULL
#5. Adjusting variable types
DT[,"RH.index"] <- factor(DT[, RH.index])
#6. Importing sample key
sample_key <- fread("sample_key.csv")
sample_key[, c("RH.index", "group")] <- sample_key[,lapply(.SD, factor), .SDcols=c("RH.index", "group")]
#7. Merging DT with sample_key
DT <- merge(DT, sample_key, by="RH.index")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Calculating number of cells divided by number of images to get comparable measure
DT_summary <- unique(DT[,.(group, days, cell_sum= sum(Count), frames=.N), by=c("RH.index")])
#2. Calculating number of cells per frame
DT_summary <- DT_summary[,cells.per.frame:=ifelse(is.nan(cell_sum/frames), 0, cell_sum/frames)][order(group, days)]
#3. Summarizing in a second step to plot error bars 
DT_summary_2 <- DT_summary[,.(Mean=mean(cells.per.frame), SD=sd(cells.per.frame), N=.N), by=c("group", "days")][,SEMx1.96:=SD/sqrt(N)][,`:=`(CI.lower=Mean-SEMx1.96, CI.upper=Mean+SEMx1.96)]
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
########################################################## STATISTICAL EVALUATION #########################################################
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Creating a list object for evaluation of assumptions 
stat_list <- split(DT_summary[!(days==20 & group=="E")], DT_summary[!(days==20 & group=="E")][,.(group,days)])
stat_list$E.20 <- NULL
#2. Evaluating normality of data within each group
normality_assumption <- do.call(rbind, lapply(stat_list, function(group.day){shapiro.test(group.day[,cells.per.frame])$p.value}))
#3. Evaluating homogenitry of variances between groups within days
homogenity_assumption <- lapply(split(DT_summary, DT_summary[,.(days)]), function(day){bartlett.test(day[,cells.per.frame], day[,group])$p.value})
#4. One-way ANOVA is appropriate since data is normally distributed and variances are homogenous
anova_objects_per_day <- lapply(split(DT_summary, DT_summary[,.(days)]), function(day){aov(cells.per.frame~group, data=day)})
#5. Retrieving p-values for multiple group comparisons for each day
p_values_day <- data.table(do.call(cbind, lapply(anova_objects_per_day, function(aov.object){summary(aov.object)[[1]][1,5]})))
#6. Tukeys post hoc test for day 3 and day 10 with significant values
tukey_test <- do.call(rbind, lapply(anova_objects_per_day, function(aov.object){data.table(attr(TukeyHSD(aov.object)$group[1:3,4], "names"), TukeyHSD(aov.object)$group[1:3,4])}))
tukey_test[,day:=c(rep(3,3), rep(10,3), rep(20,3))]
names(tukey_test) <- c("comparison","tukey.p.value", "day")
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
#1. Plotting IBA1 content per group and day 
cell_plot <- ggplot(DT_summary_2, aes(x=days, y=Mean, fill=group))+
  geom_bar(stat="identity", position = position_dodge(width=3), width=3, alpha=0.9)+
  geom_errorbar(aes(ymin=CI.lower, ymax=CI.upper), position = position_dodge(width=3), width=2, size=2)+
  geom_point(DT_summary, mapping=aes(x=days, y=cells.per.frame), position = position_dodge(width=3), size=3, alpha=0.9, show.legend = F)+

  ylab("IBA1+ cells per frame (average)")+
  xlab("Days (post SCI)")+
  
  scale_fill_manual(values=brewer.pal(11, "RdBu")[c(1,11,4)], label=c("Allogenic IDmBMSC (n=9)", "Syngeneic IDmBMSC (n=9)", "Injury control (n=9)"))+
  scale_color_manual(values=brewer.pal(11, "RdBu")[c(1,4,11)], label=c("Allogenic IDmBMSC (n=9)", "Syngeneic IDmBMSC (n=9)", "Injury control (n=9)"))+
  scale_x_continuous(breaks=seq(0,20,2))+
  scale_y_continuous(breaks=seq(0,60,5))+
  
  theme(axis.title = element_text(face="bold", size=22), axis.text = element_text(size=22), legend.position = "bottom", legend.justification = "center", legend.title = element_blank(), legend.text = element_text(size=20))+
  #p-values at 3 days
  annotate("text", x=3, y=50, label="***", size=10)+
  geom_segment(aes(x=2, xend=4, y=49,yend=49))+
  annotate("text", x=3.5, y=54, label="***", size=10)+
  geom_segment(aes(x=3, xend=4, y=53, yend=53))+
  #p-values at 10 days
  annotate("text", x=10, y=63, label="p:0.076", fontface=2, size=5)+
  geom_segment(aes(x=9, xend=11, y=61,yend=61))+
  annotate("text", x=9.5, y=67, label="p:0.055", fontface=2, size=5)+
  geom_segment(aes(x=9, xend=10, y=65,yend=65))
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
########################################################## OUTPUT #########################################################
```

```{r echo=FALSE, message=FALSE, warning=FALSE, warning=FALSE}
# #1. Saving the plot
# ggsave("cell_plot.jpg", cell_plot, width=14, height=7, dpi=1000)

# #2. Exporting the descriptive table 
# descriptive_table <- data.table(DT_summary_2[,1:2], round(DT_summary_2[,c(3,7,8)],2))
# fwrite(descriptive_table, "descriptive_table.csv", sep=";")

# #3. Exporting ANOVA table
# fwrite(data.table(type="p-vale",round(p_values_day, 4)), "anova_table.csv", sep=";")

# #4. Exporting post hoc table
# fwrite(tukey_test[,tukey.p.value:=round(tukey.p.value,4)], "post_hoc_table.csv", sep=";")
```
